// <auto-generated />
namespace PFE_reclamation.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class reclam_title : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(reclam_title));
        
        string IMigrationMetadata.Id
        {
            get { return "202008091629168_reclam_title"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
