// <auto-generated />
namespace PFE_reclamation.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class msssss : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(msssss));
        
        string IMigrationMetadata.Id
        {
            get { return "202008130913178_msssss"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
